title: thedersen.com
url: https://thedersen.com
author: Thomas Pedersen
email: thedersen@gmail.com
permalink: /blog/:year/:month/:day/:title/
feed_url: https://feeds.feedburner.com/thedersen

markdown: rdiscount
pygments: true

google_analytics_tracking_id: UA-12325477-1
disqus_short_name: thedersen
twitter_user: thedersen
